## NumPy Shape- Reshape

### <font color=pink>Recap of Past Concepts: NumPy Shapes</font>

In [ ]:
#Import numpy library
import numpy as np

In [ ]:
#Input a 2D array


In [ ]:
import numpy as np
arr=np.array([np.arange(5),np.arange(6,11),np.arange(12,17)])
print(arr)
print(('shape of array:',arr.shape))



[[ 0  1  2  3  4]
 [ 6  7  8  9 10]
 [12 13 14 15 16]]
('shape of array:', (3, 5))


### Today's topic:: Reshaping NumPy Arrays

#### <font color=violet>Reshaping NumPy Arrays</font>

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [ ]:
#Converting 1 D array to 2 D array
import numpy as np
arr=np.array([[1,2,3,4,5,6,7,8,9,10,11,12]])
new_arr=arr.reshape(4,3)
print(new_arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


#### <font color=red>Exercise: Convert 1 D Array to 3 D array. Hint: use arr.reshape(no of cells, rows, columns)</font>

In [ ]:
arr=np.arange(30)
new_arr=arr.reshape(2,3,5)
print(new_arr)


[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


### Unknown Dimensions

You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_arr=arr.reshape(2,3,-1 )
print(new_arr)




[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


## Flattening of NumPy Arrays

Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [ ]:
# Flattening of array
import numpy as np
arr=np.arange(30)
new_arr=arr.reshape(3,5,2)
new_arr2=new_arr.reshape(-1)
#new_arr2=new_arr.flatten()
print(new_arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


## Slicing of NumPy Arrays


Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [ ]:
#slice elements from index 1 to index 5

import numpy as np
new_arr=np.array([1,2,3,4,5,6,7,8])

print(new_arr[1:5])



[2 3 4 5]


In [ ]:
#Slice elements from index 4 to the end of the array:
print(new_arr[4:])


[5 6 7 8]


In [ ]:
#Slice elements from the beginning to index 4 (not included):
print(new_arr[:4])


[1 2 3 4]


## Negative Slicing

In [ ]:
import numpy as np
new_arr=np.array([1,2,3,4,5,6,7,8])

print(new_arr[-2:-1])

[7]


In [ ]:
# Some more practice
#Return every other element from index 1 to index 5:

print(new_arr[-7:-3:2])


[2 4]


In [ ]:
#Return every other element from the entire array:
print(new_arr[::2])


[1 3 5 7]


## Slicing for 2D Arrays

In [ ]:
# slice a 2D array 2nd element- 1st to 4th index
import numpy as np
arr=np.array([[1,2,3,4],
              [5,6,7,8]])
print(arr[0,1:])

[2 3 4]


In [ ]:
#From both elements, return index 2:

print(arr[:,2])

# arr[element, index]

[3 7]


In [ ]:
#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
print(arr[:,1:4])


[[2 3 4]
 [6 7 8]]


Insert the correct slicing syntax to print the following selection of the array:

Everything from (including) the second item to (not including) the fifth item


In [ ]:
import numpy as np

z=np.arange(45).reshape(3,3,5)

print(z)

z[2,:,1:4]

z[2][:,1:4]
#print(arr[])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]]]


array([[31, 32, 33],
       [36, 37, 38],
       [41, 42, 43]])

### <font color=blue>Statistics in NumPy</font>

Go through official documentation:
https://numpy.org/doc/stable/reference/routines.statistics.html

In [ ]:
# pick up anything-- lets pick up percentile
import numpy as np
a=np.array([[10,7,4],[3,2,1]])
a
np.percentile(a,50)

import numpy as np
a=np.array([[10,7,4],[3,2,1]])
print(a)
#print(np.percentile(a,50))
#print(np.percentile(a,50,axis=0))

print(np.mean(a,axis=0))



a=np.array([[1,2 ],[3,4]])
print(a)
print(np.percentile(a,100,axis=1,keepdims=True))
#print(np.percentile(a,50,axis=0))

#print(np.mean(a,axis=1))


a=np.array([[1,2 ],[3,4],[5,6 ]])
print(a)
print(np.percentile(a,100,axis=1,keepdims=True))#2D
#print(np.percentile(a,50,axis=0))

print(np.mean(a,axis=1))


a=np.array([[1,2 ],[3,4],[5,6]])
print(a)
#print(np.percentile(a,50,axis=0))
print(np.percentile(a,100,axis=1,keepdims=True))#2D

#print(np.mean(a,axis=1))


print(a.sum(axis=1))

[[10  7  4]
 [ 3  2  1]]
[6.5 4.5 2.5]
[[1 2]
 [3 4]]
[[2.]
 [4.]]
[[1 2]
 [3 4]
 [5 6]]
[[2.]
 [4.]
 [6.]]
[1.5 3.5 5.5]
[[1 2]
 [3 4]
 [5 6]]
[[2.]
 [4.]
 [6.]]
[ 3  7 11]


### Again NumPy Stat Topics to be read & learnt:

Numpy Percentile,
Numpy.ptp(Range),
Numpy.mean(),
Median,
Mode,
Standard Deviation,
Variance


#Read about Binomial & Poisson distribution although seldom asked

https://www.w3schools.com/python/numpy/numpy_random_binomial.asp



https://www.w3schools.com/python/numpy/numpy_random_poisson.asp

Ready for Quiz? Let's practice some questions

Question 1: Given are 2 similar dimensional numpy arrays, how to get a numpy array output in which every element is an element-wise sum of the 2 numpy arrays?

In [ ]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[10,11,12],
              [13,14,15]])
# your code here
x=a+b
x
y=np.add(a,b)
y



array([[11, 13, 15],
       [17, 19, 21]])

Question 2: Given a numpy array (matrix), how to get a numpy array output which is equal to the original matrix multiplied by a scalar?

In [ ]:
a = np.array([[1,2,3],
              [4,5,6]])
# your code here
x=a*5
x
y=np.multiply(a,b)
y

array([[10, 22, 36],
       [52, 70, 90]])

Question 3: Create an identity matrix of dimension 4-by-4 scalar?

In [ ]:
np.identity(4)
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Question 4: Convert a 1 D array into 3 D array

In [ ]:

arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr.reshape((2,3,2))

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

Question 5: Convert all the elements of a numpy array from integer to complex datatype



In [ ]:
a = np.array([[2.5, 3.8, 1.5],
             [4.7, 2.9, 1.56]])
a.astype(complex)
np.complex_(a)

np.array(a,dtype=complex)


array([[2.5 +0.j, 3.8 +0.j, 1.5 +0.j],
       [4.7 +0.j, 2.9 +0.j, 1.56+0.j]])

Question 6:Stack 2 numpy arrays horizontally i.e., 2 arrays having the same 1st dimension (number of rows in 2D arrays)

In [ ]:
a1 = np.array([[1,2,3],
               [4,5,6]])

a2 = np.array([[7,8,9],
               [10,11,12]])
np.hstack((a1,a2))



array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

Question 7: From 2 arrays in numpy, extract the indexes in which the elements in the 2 arrays are in the same positions


In [ ]:
a = np.array([1,2,3,4,5])

b = np.array([1,3,2,4,5])
np.where(a==b)



(array([0, 3, 4]),)

Question 8: Output the transpose of a matrix (as numpy array)


In [ ]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
np.transpose(a)
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## Interview Question links(Please go through them before attempting quiz/interviews

https://www.hackertrail.com/talent/backend/numpy-interview-questions-answers/



Some more useful pieces of code

In [ ]:
arr = np.array([0, 5, 4, 0, 4, 4, 3, 0, 0, 5, 2, 1, 1, 9])

np.bincount(arr)

array([4, 2, 1, 1, 3, 2, 0, 0, 0, 1])